services:
  postgres:
    image: yordy/postgres:v16.1
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: yordy/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/monodb/data
  rabbitmq:
    image: yordy/rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672    
volumes:
  pgdata:
  mongodata: